version: "3.9"
services:
  notification:
    build: .
    ports:
      - "6000:6000"
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo 10.10.10.60:27017/db --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      
volumes:
  mongodb:
    driver: local
  mongoconfig:
