version: '3.8'
services:
  notification:
    build: .
    ports:
    - "5001:5000"
    volumes:
    - .:/opt
    links:
    - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: Secret
    volumes:
      - mongo-data:/data/db 
      - mongo-configdb:/data/configdb
    command: mongod  --port 27017

volumes:
  mongo-data:
  mongo-configdb:
